//
// Created by awsle on 22/03/2022.
//

#ifndef PA1_ASSIGNMENT_MACROS_H
#define PA1_ASSIGNMENT_MACROS_H

#ifndef _WINSOCK_DEPRECATED_NO_WARNINGS
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <Windows.h>
#pragma comment(lib, "Ws2_32.lib")


#define FDATA_BITS		26												// BITS TO ENCODE
#define BYTES_IN_FRAME			31												// ENCODED BITS
#define PARITY_BITS	5												// PARITY BITS
#define FRAMES_IN_PACKET		31												// ENCODED ELEMENTS IN PACKET
#define BYTES_IN_PACKET			FRAMES_IN_PACKET * BYTES_IN_FRAME * 20			// PACKET BYTES
#define DATA_BYTES_IN_PACKET	FRAMES_IN_PACKET * DATA_BYTES_IN_FRAME
#define FILENAME_SIZE					500												// MAX FILENAME


#endif //PA1_ASSIGNMENT_MACROS_H
